---
openapi: 3.0.3
info:
  title: KT Cloud Bizstore 서비스 API
  description: API 인증은 JWT 형식으로 하며, JWT 토큰 생성 및 검증을 위한 상세 명세(Header, Payload, Public Key)는 아래 'JWT 토큰 생성을 위한 문서'를 참조합니다. JWT의 유효시간은 1분입니다. JWT Token내 signautre 부분에 ",포함 Private key는 입력하지 않음. Public key는 별도로 요청해 주세요. 
  version: 2.1.0
externalDocs:
  description: JWT 토큰 생성을 위한 문서
  url: https://jwt.io/#debugger-io?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3QgY2xvdWQgYml6IHN0b3JlIiwiaWF0IjoxNjEzMjM5MDIyfQ.Aj4dRXjzLyobZQTpxOO3p66Dq5mrBPKCb5XtD-gmhxI128la6p_CdKzLI7X2j_eFFRXQL2zf8Q7tZ2NcTJ8Pz7nq1xitp77JsBLCNBjvOqKwEmIf9R3kci2uJinkGj-xiGq3gplBOZ0jeBKv60Lt1nmKZ-LvmFh_Kf3WMTwFDOVlrwPgvXYMK4qyyCRG3JGFTjMQNX7JrNnoUfU9D8lDDsAI21fksmSU_SHEVJnc172VfXOt2UMb4eAcBP3Sk8x6MEwGXQXKp2ltEhh3NNMgY7VaKD7iPEg1--D_9g_7XuVmAqkUhm3ZcAo6dKgdXA9t99xh8TY3cbsY_QEv4dyqbQ&publicKey=-----BEGIN%20PUBLIC%20KEY-----%0AMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnzyis1ZjfNB0bBgKFMSv%0AvkTtwlvBsaJq7S5wA%2BkzeVOVpVWwkWdVha4s38XM%2Fpa%2Fyr47av7%2Bz3VTmvDRyAHc%0AaT92whREFpLv9cj5lTeJSibyr%2FMrm%2FYtjCZVWgaOYIhwrXwKLqPr%2F11inWsAkfIy%0AtvHWTxZYEcXLgAXFuUuaS3uF9gEiNQwzGTU1v0FqkqTBr4B8nW3HCN47XUu0t8Y0%0Ae%2Blf4s4OxQawWD79J9%2F5d3Ry0vbV3Am1FtGJiJvOwRsIfVChDpYStTcHTCMqtvWb%0AV6L11BWkpzGXSW4Hv43qa%2BGSYOD2QU68Mb59oSk2OB%2BBtOLpJofmbGEGgvmwyCI9%0AMwIDAQAB%0A-----END%20PUBLIC%20KEY-----
servers:
- url: https://연동대상시스템의 URL
  description: https를 사용해야 하며 SSL 인증서를 KT Cloud 포탈에 공유해야합니다. 연동대상시스템의 IP는 하나로 지정하여 통신합니다.
paths:
  /status/{mem-sq}:
    get:
      tags:
      - status-management
      summary: 서비스 상태값 조회
      description: 고객의 서비스 상태값 조회(구축형일 경우 구축중인지 확인 필요)
      parameters:
      - name: encoded-jwt
        in: header
        description: JWT를 통한 권한 확인
        required: false
        style: simple
        explode: false
        schema:
          type: string
          description: https://jwt.io/introduction을 따름. 상세 내용은 JWT 토큰 생성을 위한 문서 확인
          format: '{header}.{payload}.{signature}'
      - name: mem-sq
        in: path
        description: KT Cloud가 보유하고 있는 고유의 고객 식별자
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: M12345
      responses:
        "200":
          description: 유효한 요청에 대한 올바른 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/status'
        "401":
          description: not_match_authorization = authKey 에러
        default:
          description: 예상못한 에러
      security:
      - tokenAuth: []
  /customers/{mem-sq}:
    post:
      tags:
      - customer-management
      summary: 서비스 신청, SSO 연동 관련 API.
      description: token값과 함께 고객정보를 연동대상시스템으로 전달하여 서비스 신청.
      parameters:
      - name: encoded-jwt
        in: header
        description: JWT를 통한 권한 확인
        required: false
        style: simple
        explode: false
        schema:
          type: string
          description: https://jwt.io/introduction을 따름. 상세 내용은 JWT 토큰 생성을 위한 문서 확인
          format: '{header}.{payload}.{signature}'
      - name: mem-sq
        in: path
        description: KT Cloud가 보유하고 있는 고유의 고객 식별자
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: M12345
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/customer-body'
      responses:
        "200":
          description: OK. 고객에게 정상적으로 연동대상시스템의 로그인 페이지를 전달합니다.
          headers:
            Location:
              description: 연동대상시스템의 로그인페이지
              schema:
                type: string
                example: 'http://연동대상시스템URL/SSO_URI?Query'
          content:
            text/html:
              schema:
                description: 고객에게 보여줄 html page
                type: string
                example: '{"html":{"summary":"고객에게 보여줄 html page","value":"<html>....</html>"}}'
        "201":
          description: Creadted. 서비스 신청 완료된 경우, 고객에게 정상적으로 연동대상시스템의 로그인 페이지를 전달합니다.        
          headers:
            Location:
              description: 연동대상시스템의 로그인페이지
              schema:
                type: string
                example: 'http://연동대상시스템URL/SSO_URI?Query'
          content:
            text/html:
              schema:
                properties:
                  Location:
                    description: 고객에게 보여줄 html page
                    type: string
                    example: '{"html":{"summary":"","value":"<html>....</html>"}}'
        "401":
          description: not_match_authorization = authKey 에러
        default:
          description: 예상못한 에러
    delete:
      tags:
      - customer-management
      summary: 고객 탈퇴
      description: 고객 탈퇴처리를 위해 mem-sq에 해당하는 고객 레코드에 탈퇴일을 추가합니다. (Auth Key 값은 Basic 값 입니다.)
      parameters:
      - name: encoded-jwt
        in: header
        description: JWT를 통한 권한 확인
        required: true
        schema:
          type: string
          description: https://jwt.io/introduction을 따름. 상세 내용은 JWT 토큰 생성을 위한 문서 확인
          format: '{header}.{payload}.{signature}'
      - name: mem-sq
        in: path
        description: KT Cloud가 보유하고 있는 고유의 고객 식별자
        required: true
        schema:
          type: string
        example: M12345
      responses:
        "200":
          description: 유효한 요청에 대한 올바른 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "401":
          description: not_match_authorization = authKey 에러
        default:
          description: 예상못한 에러
      security:
      - tokenAuth: []
  /bill-list/date/{bill-day}:
    get:
      tags:
      - billing-management
      summary: 날짜별 과금정보 조회
      description: 연동 시스템에서 보유한 특정 일 곧 {bill-day}까지 과금했을 때의 요금을 회신합니다.
      parameters:
      - name: encoded-jwt
        in: header
        description: JWT를 통한 권한 확인
        required: false
        schema:
          type: string
          description: https://jwt.io/introduction을 따름. 상세 내용은 JWT 토큰 생성을 위한 문서 확인
          format: '{header}.{payload}.{signature}'
      - name: bill-day
        in: path
        description: 조회하고 싶은 일자를 의미합니다.(해당 일의 요금 정보를 회신. 해당 월 요금 기준으로 일할 계산)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: yyyy-mm-dd
          example: 2021-02-09T00:00:00.000+0000
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bills'
        default:
          $ref: '#/components/responses'
  /bill-list/customer/{mem-sq}:
    get:
      tags:
      - billing-management
      summary: 사용자별 과금정보 조회
      description: 특정 고객에 대한 가입일부터 현재까지의 각 일별로 과금 정보를 회신합니다.
      parameters:
      - name: encoded-jwt
        in: header
        description: JWT를 통한 권한 확인
        required: false
        style: simple
        explode: false
        schema:
          type: string
          description: https://jwt.io/introduction을 따름. Base64Url({header}).Base64Url({payload}).Base64Url(signature)
          format: '{header}.{payload}.{signature}'
      - name: mem-sq
        in: path
        description: KT Cloud가 보유하고 있는 고유의 고객 식별자
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
      security:
      - tokenAuth: []
components:
  schemas:
    Bills:
      type: array
      items:
        $ref: '#/components/schemas/Bill'
    Bill:
      required:
      - bill-date
      - service-info
      - license-count
      - free-period
      - mem-sq
      - pay-amt
      properties:
        mem-sq:
          type: string
          format: UTF-8
        bill-date:
          type: string
          format: yyyy-mm-dd
        service-info:
          type: string
          description: 해당 서비스 정보로 '서비스유형(납부유형)'형식을 갖춤
          example: standard(초기 납부제)
        free-period:
          type: string
          description: 시작일~종료일
          format: yyyymmdd~yyyymmdd
          example: 20210301~202010501
        contract-discount-period:
          type: string
          description: 시작일~종료일
          format: yyyymmdd~yyyymmdd
          example: 20210301~202010501
        license-count:
          type: string
          description: 사용량
        usage-pay-amt:
          type: integer
          description: license-count 기반 요금 (KRW 단위)
          format: int32
        onetime-start:
          type: string
          format: yyyy-mm-dd
        onetime-pay-amt:
          type: integer
          description: onetime 기반 요금 (KRW 단위)
          format: int32
        pay-amt:
          type: integer
          description: license-count + onetime 기반 요금, 전체 요금(KRW 단위)
          format: int32
    customer-body:
      type: object
      properties:
        service-info:
          type: integer
          description: 해당 서비스 정보로 '서비스유형(납부유형)'을 코드화한 값
          example: 1
        onetime-type:
          type: integer
          description: 도입비 분할 여부를 코드화한 값
          example: 1
        contract-period:
          type: integer
          description: 약정기간 구분 코드
          example: 1
        contract-discount-period:
          type: string
          description: 시작일~종료일
          format: yyyymmdd~yyyymmdd
          example: 20210301~202010501
        onetime-start:
          type: string
          format: yyyy-mm-dd
        license-start-date:
          type: string
          description: 라이선스 시작 일 (yyyyMMdd)
          example: "20201210"
        license-end-date:
          type: string
          description: 라이선스 종료 일 (yyyyMMdd)
          example: "2021030"
        product-id:
          type: string
          description: 라이선스 구분(무료 = 0, 유료 요금제 A = 1, 유료 요금제 B = 2)
          example: "1"
        license-states-cd:
          type: string
          description: 라이선스 상태(사용중 = 0, 해지 = 1, 정지 = 2)
          example: "0"
    inline_response_200:
      required:
      - description
      - success
      properties:
        success:
          description: 성공 실패 여부를 의미한다.
          example: true or false
        description:
          description: 실패 여부의 상세 원인을 표현한다.
    status:
      required:
      - mem-sq
      - reg-date
      - install-complete-date
      - status
      - service-manager
      - service-engineer
      properties:
        mem-sq:
          description: 고객 식별정보
          example: M12345
        reg-date:
          description: 고객 신청일 
          format: yyyy-mm-dd
          example: 2021-04-28
        install-complete-date:
          description: 설치 완료일 
          format: yyyy-mm-dd
          example: 2021-04-28
        status:
          description: 설치진행중 - 설치 완료 / 삭제진행중 - 삭제 완료
          example: 설치 완료 
        service-manager:
          description: 서비스 담당자 정보 
          example: 홍길동(010-3333-4444,honggildong@kt.com)
          format: name(010-nnnn-nnnn,name@domain)
        service-engineer:
          description: 서비스 엔지니어 정보
          example: 홍길동(010-3333-4444,honggildong@kt.com)
          format: name(010-nnnn-nnnn,name@domain)
  responses:
    "200":
      description: 성공, OK, 유효한 요청에 대한 예상된 응답
    "201":
      description: 성공, Created, 자원 생성 완료
    "202":
      description: 성공, Accepted, 시간 지연
    "400":
      description: 실패, Bad request
    "401":
      description: 실패, Unauthorized, 유저 권한 없음
    "403":
      description: 실패, Forbidden, 유저 권한 문제
    "404":
      description: 실패, Not Found, 찾지 못함.
    "405":
      description: 실패, Method not allowed, Request의 endpoint와 resource가 유효하지 않음.
    "406":
      description: 실패, 무료체험 고객
  securitySchemes:
    tokenAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
