---
openapi: 3.0.3
info:
  title: KT Cloud Bizstore 서비스 API
  description: SSL 인증으로 진행합니다. SSL Client 인증서를 KT Cloud 포탈에 공유해야합니다. 연동대상시스템의 IP는 하나로 지정하여 통신합니다. 
  version: 3.0.0
servers:
- url: https://연동대상시스템의 URL
  description: URL은 SSL Client 인증서와 같이 사전에 KT로 공유되어야 합니다.
paths:
  /status/:
    get:
      tags:
      - status-management
      summary: 서비스 상태값 조회
      description: 고객의 서비스 상태값 조회
      responses:
        "200":
          description: 유효한 요청에 대한 올바른 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/status'
        default:
          description: 예상못한 에러
  /customers/:
    post:
      tags:
      - customer-management
      summary: 서비스 신청 및 SSO
      description: 고객정보를 연동대상시스템으로 전달하여 서비스 신청. 이미 신청된 고객이면 SSO로그인 처리 
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/customer-body'
      responses:
        "302":
          description: Redirect
          headers:
            Location:
              description: 연동대상시스템의 로그인페이지
              schema:
                type: string
                format: uri
                example: 'http://연동대상시스템URL/SSO_URI?Query'
        default:
          $ref : '#/components/responses'
    delete:
      tags:
      - customer-management
      summary: 고객 탈퇴
      description: 고객 탈퇴처리를 위해 mem-sq에 해당하는 고객 레코드에 탈퇴일을 추가합니다. 
      requestBody:
        content:
          "application/json":
            schema:
              required:
                - "mem-sq"
              properties:
                "mem-sq" :
                  type: string
                  example : M12345
      responses:
        default:
          $ref : '#/components/responses'
  /bill-list/date/{bill-day}:
    get:
      tags:
      - billing-management
      summary: 날짜별 과금정보 조회
      description: 연동 시스템에서 보유한 특정 일 곧 {bill-day}까지 과금했을 때의 요금을 회신합니다.
      parameters:
      - name: bill-day
        in: path
        description: 조회하고 싶은 일자를 의미합니다.(해당 일의 요금 정보를 회신. 해당 월 요금 기준으로 일할 계산)
        required: true
        schema:
          type: string
          format: yyyymmdd
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bills'
        default:
          $ref: '#/components/responses'
  /bill-list/customer/:
    get:
      tags:
      - billing-management
      summary: 사용자별 과금정보 조회
      description: 특정 고객에 대한 가입일부터 현재까지의 각 일별로 과금 정보를 회신합니다.
      requestBody:
        content:
          "application/json":
            schema:
              required:
                - "email"
              properties:
                "email" :
                  type: string
                  example : test@kt.com
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
        default:
          $ref: '#/components/responses'
components:
  schemas:
    customer-body:
     type: object
     properties:
        mem-sq:
          type: string
          description: 고객식별 정보 
          example: "M12345"
        license-info:
          type: string
          description: 해당 서비스 정보로 '서비스 요금제 유형(납부유형)'을 코드화한 값(2=standard, 3=premium, 4=public, 5=enterprise)
          example: "2"
          enum: [2,3,4,5]
        contract-discount-period:
          type: string
          description: 약정할인 기간(시작일~종료일)
          format: yyyymmdd~yyyymmdd
          example: 20210301~202010501
        contract-discount-percentage:
          type: string
          description: 약정할인율(%)
          example: 10
        license-states-cd:
          type: string
          description: 라이선스 상태(사용중 = 0, 해지 = 1, 정지 = 2)
          example: "0"
    Bills:
      type: array
      items:
        $ref: '#/components/schemas/Bill'
    Bill:
      required:
      - mem-sq
      - bill-date
      - pay-amt
      properties:
        mem-sq:
          type: string
          format: UTF-8
        bill-date:
          type: string
          format: yyyymmdd
        pay-amt:
          type: string
          description: 1일부터 yyyymmdd까지 사용했을 때의 요금   
    inline_response_200:
      required:
      - description
      - success
      properties:
        success:
          description: 성공 실패 여부를 의미한다.
          example: true or false
        description:
          description: 실패 여부의 상세 원인을 표현한다.
    status:
      required:
      - mem-sq
      - free-period
      - license-info
      - license-count
      - license-start-date
      - install-status
      - install-complete-date
      - service-manager
      - service-engineer
      properties:
        mem-sq:
          description: 고객 식별정보
          example: M12345
        free-period:
          description: 무료 사용 기간
          example: yyyymmdd ~ yyyymmdd
        license-info:
          description: 사용자가 사용하는 요금제 정보 (Basic = 0, Preminum = 1)
          example: 0
        license-count:
          description: 사용자 수 
          example: 50
        license-start-date:
          description: 고객 신청일(kt cloud bizstore 신청기준)
          format: yyyymmdd
          example: 20210428
        install-status:
          description: 설치 상태 (설치진행 중 = 0, 설치 완료 = 1, 삭제 진행 중 = 2, 삭제 완료 = 3)
          example: 0
        install-complete-date:
          description: 설치 완료일.
          format: yyyymmdd
          example: 20210428 (설치 진행 중일 땐 99999999 (기본값))
        service-manager:
          description: 서비스 담당자 정보 
          example: 홍길동(010-3333-4444,honggildong@kt.com)
          format: name(010-nnnn-nnnn,name@domain)
        service-engineer:
          description: 서비스 엔지니어 정보
          example: 홍길동(010-3333-4444,honggildong@kt.com)
          format: name(010-nnnn-nnnn,name@domain)
  responses:
    "200":
      description: 성공, OK, 유효한 요청에 대한 예상된 응답
    "201":
      description: 성공, Created, 자원 생성 완료
    "202":
      description: 성공, Accepted, 시간 지연
    "400":
      description: 실패, Bad request, 상세한 실패 원인 회신 할 것.
    "401":
      description: 실패, Unauthorized, 유저 권한 없음
    "403":
      description: 실패, Forbidden, 유저 권한 문제
    "404":
      description: 실패, Not Found, 찾지 못함.
    "405":
      description: 실패, Method not allowed, Request의 endpoint와 resource가 유효하지 않음.
    "406":
      description: 실패, 무료체험 고객
