---
openapi: 3.0.3
info:
  title: KT Cloud Bizstore KT DaaS 서비스 API
  description: SSL 인증으로 진행합니다. 
  version: 3.0.1
servers:
- url: https://연동대상시스템의 URL
  description: https를 사용해야 하며 SSL 인증서를 KT Cloud 포탈에 공유해야합니다. 연동대상시스템의 IP는 하나로 지정하여 통신합니다.
paths:
  /status/:
    get:
      tags:
      - status-management
      summary: 서비스 상태값 조회
      description: 고객의 서비스 상태값 조회
      responses:
        "200":
          description: 유효한 요청에 대한 올바른 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        default:
          description: 예상못한 에러
  /customers/:
    post:
      tags:
      - customer-management
      summary: 서비스 신청, SSO 연동 관련 API.
      description: 고객정보를 연동대상시스템으로 전달하여 서비스 신청.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        default:
          $ref : '#/components/responses'
    delete:
      tags:
      - customer-management
      summary: 고객 탈퇴
      description: 고객 탈퇴처리를 위해 email에 해당하는 고객을 전달합니다.
      requestBody:
        content:
          "application/json":
            schema:
              required:
                - "email"
              properties:
                "email" :
                  type: string
                  example : test@kt.com
      responses:
        default:
          $ref : '#/components/responses'
  /bill-list/date/{bill-date}:
    get:
      tags:
      - billing-management
      summary: 날짜별 사용정보 조회
      description: "bill-data까지의 사용량 정보를 얻기 위한 API 입니다."
      parameters:
      - name: bill-date
        in: path
        description: 조회하고 싶은 일자를 의미합니다.(해당 일의 사용 정보 회신. 해당 월 요금 기준으로 일할 계산)
        required: true
        schema:
          type: string
          format: yyyymmdd
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bills'
        default:
          $ref: '#/components/responses'
  /bill-list/customer/:
    get:
      tags:
      - billing-management
      summary: 사용자별 과금정보 조회
      description: 특정 고객에 대한 가입일부터 현재까지의 각 일별로 과금 정보를 회신합니다.
      requestBody:
        content:
          "application/json":
            schema:
              required:
                - "email"
              properties:
                "email" :
                  type: string
                  example : test@kt.com
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
        default:
          $ref: '#/components/responses'
components:
  schemas:
    Customer:
      type: object
      properties:
        email:
          type: string
          description: 고객식별 정보 
          example: "honggildong@kt.com"
        business-name:
            type: string
            description: 사업자 이름
            example: "삼성"
        business-num:
            type: string 
            description: 사업자 번호 
            example: "123-345-2345"
        configuration:
            type: string
            description: 구성정보로 Pool이나 Dedicated로 표현할 것. 
            example: "Pool"
    Bills:
      type: array
      items:
        $ref: '#/components/schemas/Bill'
    Bill:
      required:
      - bill-date
      - email
      - vm-status
      properties:
        bill-date:
          type: string
          format: yyyy-mm-dd
        email:
          type: string
          example: honggildong@kt.com
        vm-status:
          type: array
          items:
            $ref: '#/components/schemas/VMs'
    VMs:
      type: object
      properties:
        vm-name:
          type: string
          example: "NC0101"
        vm-spec:
          type: string 
          example: "2 vCore:8G Mem"
        usage-time:
          type: integer 
          description: 사용시간(seconds)
          example: 123432
    Status:
      required:
      - email
      - reg-date
      - status
      - location
      - announceMail
      - service-manager
      - service-engineer
      properties:
        email:
          type: string
          description: 고객 식별정보
          example: "honggildong@kt.com"
        reg-date:
          description: 고객 신청일
          format: yyyymmdd
          example: 20210428
        start-date:
          description: 서비스 시작일
          format: yyyymmdd
          example: 20210818
        status:
          type: string
          description: 현재 사용 여부 회신
          example: "설치 중","사용 중","삭제 진행 중","삭제 완료 중"
        location:
          type: string
          description: 고객이 기업DaaS에 접속하기 위한 URL 
          exmaple: honggildong.vdi.kt.com
        announceMail:
          type: string
          description: location과 DaaS 구축이 완료되었을때 공지를 수신하는 메일
          exmaple: honggildong@kt.com
  responses:
    "200":
      description: 성공, OK, 유효한 요청에 대한 예상된 응답
    "201":
      description: 성공, Created, 자원 생성 완료
    "202":
      description: 성공, Accepted, 시간 지연
    "400":
      description: 실패, Bad request, 상세한 실패 원인 회신 할 것.
    "401":
      description: 실패, Unauthorized, 유저 권한 없음
    "403":
      description: 실패, Forbidden, 유저 권한 문제
    "404":
      description: 실패, Not Found, 찾지 못함.
    "405":
      description: 실패, Method not allowed, Request의 endpoint와 resource가 유효하지 않음.
    "406":
      description: 실패, 무료체험 고객
