---
openapi: 3.0.3
info:
  title: KT Cloud BizOffice 서비스 API
  version: 2.1.2
  description: OpenAPI 규격확인은 'https://swagger.io/specification/'를 참고합니다.
servers:
- url: https://연동대상시스템의 URL
  description: https를 사용해야 하며 SSL 인증서를 KT Cloud 포탈에 공유해야합니다. 연동대상시스템의 IP는 하나로 지정하여 통신합니다.
paths:
  /status/:
    get:
      tags:
      - status-managent
      summary: 고객 전체에 대한 서비스 상태값 조회 
      parameters:
        - name: mem-sq
          in: path
          description: 고객 식별정보, 'all' keyword를 mem-sq 로 넣으면 전체 고객에 대한 정보가 return 됨. 
          required: true
          schema:
            type: string
            format: (M)nnnnn
            example: "all"
      responses:
        "200":
          description: 요청 내역에 대한 정상 응답
          content: 
            "application/json":
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/status'
        default:
            description: 200응답 외로 응답값은 아래로 처리할 것.
            content:
              application/json:
                schema:
                  $ref: '#/components/responses'
  /customers/:
    post:
      tags:
      - customer-management
      summary: 서비스 신청, SSO 연동 관련 API.
      description: 고객정보를 연동대상시스템으로 전달하여 서비스 신청
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/customer-body'
      responses:
        "201":
          description: Creadted. 서비스 신청 완료된 경우, 고객에게 정상적으로 연동대상시스템의 로그인 페이지를 전달합니다.        
          headers:
            Location:
              description: 연동대상시스템의 로그인페이지
              schema:
                type: string
                example: 'http://연동대상시스템URL/SSO_URI?Query'
          content:
            application/json:
              schema:
                type: object
                properties:
                  html:
                    type: object
                    properties:
                      summary:
                        type: string
                        description: 용도
                        example: "그룹웨어 가입 신청 페이지"
                      value:
                        description: 연동대상시스템의 로그인페이지
                        type: string
                        example: http://연동대상시스템URL/SSO_URI?Query
        default:
          description: 200응답 외로 응답값은 아래로 처리할 것.
          content:
            application/json:
              schema:
                $ref: '#/components/responses'
    delete:
      tags:
      - customer-management
      summary: 고객 탈퇴
      description: 고객 탈퇴처리를 위해 mem-sq에 해당하는 고객 레코드에 탈퇴일을 추가합니다. (Auth Key 값은 Basic 값 입니다.)
      parameters:
      - name: mem-sq
        in: path
        description: 고객 식별정보
        required: true
        schema:
          type: string
          format: (M)nnnnn
      responses:
        default:
          description: 요청에 대한 기본 응답값
          content:
            application/json:
              schema:
                $ref: '#/components/responses'
  /customers/change-status/:
    put:
      tags:
      - customer-management
      summary: 이용 정지
      description: 고객의 이용 상태 변경에 대한 처리를 함. 
      requestBody:
        content:
          "application/json":
            schema:
              required:
                - "mem-sq"
                - "status"
              properties:
                mem-sq:
                  type: string
                  description: KT Cloud에서의 고객 식별 정보
                  example: M123456
                status:
                  type: string
                  enum: ["이용재개", "이용중지"]
      responses:
        "200":
          description: "정상 응답"
          content:
            "application/json":
              schema:
                required:
                  - "result"
                  - "description"
                properties:
                  result:
                    enum: ["succeed","fail"]
                  description:
                    type: string
                    example: "ㅇㅇㅇ가 잘못되었습니다. <- 설명은 상세하게 표현할 것."
  /customers/change-bill-status/:
    put:
      tags:
      - customer-management
      summary: 과금 상태 변경
      description: 고객의 과금 상태를 변경하는 API
      requestBody:
        content:
          "application/json":
            schema:
              required:
                - "mem-sq"
                - "status"
              properties:
                mem-sq:
                  type: string
                  description: KT Cloud에서의 고객 식별 정보
                  example: M123456
                status:
                  type: string
                  enum: ["과금시작", "과금중지"]
      responses:
        "200":
          description: "정상 응답"
          content:
            "application/json":
              schema:
                required:
                  - "result"
                  - "description"
                properties:
                  result:
                    enum: ["succeed","fail"]
                  description:
                    type: string
                    example: "ㅇㅇㅇ가 잘못되었습니다. <- 설명은 상세하게 표현할 것."
  /customers/change-service/:
    put:
      tags:
      - customer service management
      summary: 서비스 변경 
      description: 고객이 소유한 서비스를 변경하도록 함. 
      requestBody:
        content:
          "application/json":
            schema:
              required:
                - "mem-sq"
                - "change-count-Of-Id"
                - "change-common-volume"
                - "change-email-volume"
              properties:
                mem-sq:
                  type: string
                  description: KT Cloud에서의 고객 식별 정보 
                  example: M12345
                change-count-Of-Id:
                  type: integer
                  description: 단위는 갯수
                change-common-volume:
                  type: object 
                  description: 사용자가 추가한 공용 용량 갯수
                  properties:
                    one-giga-change-volume-cnt: 
                      type: integer 
                      example: 3 
                    one-hundred-giga-change-volume-cnt:
                      type: integer 
                      example: 2 
                    five-hundreds-giga-change-volume-cnt:
                      type : integer 
                      example: 1 
                change-email-volume:
                  type: object 
                  description: 사용자가 추가한 공용 용량 갯수
                  properties:
                    one-giga-change-volume-cnt: 
                      type: integer 
                      example: 3 
                    one-hundred-giga-change-volume-cnt:
                      type: integer 
                      example: 2 
                    five-hundreds-giga-change-volume-cnt:
                      type : integer 
                      example: 1
      responses:
        "200":
          description: "정상 응답"
          content:
            "application/json":
              schema:
                required:
                  - "result"
                  - "volume"
                properties:
                  result:
                    enum: ["succeed","fail"]
                  description: 
                    type: "string"
                    description: 성공 및 실패에 대한 상세한 사유
                    example: "xxx 때문에 실패했습니다."
                  volume:
                    type: object
                    required:
                      - total-count-of-id
                      - total-common-volume
                      - total-email-volume
                    properties:
                      total_count-of-id:
                        type: integer
                        description:  id 변경후 최종 id 수량 
                      total-common-volume:
                        type: object
                        description: 공용 용량 
                        properties:
                          one-giga-change-volume-cnt: 
                            type: integer 
                            example: 3 
                          one-hundred-giga-change-volume-cnt:
                            type: integer 
                            example: 2 
                          five-hundreds-giga-change-volume-cnt:
                            type : integer 
                            example: 1 
                      total-email-volume:
                        type: object
                        description: 공용 용량 
                        properties:
                          one-giga-change-volume-cnt: 
                            type: integer 
                            example: 3 
                          one-hundred-giga-change-volume-cnt:
                            type: integer 
                            example: 2 
                          five-hundreds-giga-change-volume-cnt:
                            type : integer 
                            example: 1 
  /bill-list/date/{bill-date}:
    get:
      tags:
      - billing-management
      summary: 날짜별 사용정보 조회
      description: "bill-data까지의 사용량 정보를 얻기 위한 API 입니다."
      parameters:
      - name: bill-date
        in: path
        description: 조회하고 싶은 일자를 의미합니다.(해당 일의 사용 정보 회신. 해당 월 요금 기준으로 일할 계산)
        required: true
        schema:
          type: string
          format: yyyymmdd
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bills'
        default:
          $ref: '#/components/responses'
  /bill-list/customer/:
    get:
      tags:
      - billing-management
      summary: 사용자별 과금정보 조회
      description: 특정 고객에 대한 가입일부터 현재까지의 각 일별로 과금 정보를 회신합니다.
      requestBody:
        content:
          "application/json":
            schema:
              required:
                - "mem-sq"
              properties:
                "mem-sq" :
                  type: string
                  description: 고객식별 정보
                  example : "M12345"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
        default:
          $ref: '#/components/responses'
components:
  schemas:
    Bills:
      type: array
      items:
        $ref: '#/components/schemas/Bill'
    Bill:
      type: object
      properties:
        mem-sq:
          type: string
          description: 고객식별정보
          example: M123455
        bill-date:
          type: string
          format: yyyy-mm-dd
        free-period:
          type: string
          description: 시작일~종료일
          format: yyyymmdd~yyyymmdd
          example: "20210301~202010501"
        contract-discount-period:
          type: string
          description: 시작일~종료일
          format: yyyymmdd~yyyymmdd
          example: "20210301~202010501"
        count-of-id:
          type: integer
          description:  현재 고객이 사용하는 id 수량 
        common-volume:
          type: object 
          description: 사용자가 추가한 공용 용량 갯수
          properties:
            one-giga-volume-cnt: 
              type: integer 
              example: 3 
            one-hundred-giga-volume-cnt:
              type: integer 
              example: 2 
            five-hundreds-giga-volume-cnt:
              type : integer 
              example: 1 
        email-volume:
          type: object 
          description: 사용자가 추가한 공용 용량 갯수
          properties:
            one-giga-volume-cnt: 
              type: integer 
              example: 3 
            one-hundred-giga-volume-cnt:
              type: integer 
              example: 2 
            five-hundreds-giga-volume-cnt:
              type : integer 
              example: 1 
        pay-amt:
          type: integer
          description: 요금(KRW 단위, VAT 제외), 약정 할인 및 공용 용량, 전자메일 용량이 반영된 요금(bill date 해당 월 1일부터 bill date까지 반영. 누적 값), 해지해도 조회가 됨.
          format: int32
    customer-body:
      type: object
      properties:
        mem-sq:
          type: string
          description: 고객 식별 정보 (포탈에서의)
          example: "M12345"
        count-of-id:
          type: integer
          description:  현재 고객이 사용하는 id 수량 
        common-volume:
          type: object 
          description: 사용자가 추가한 공용 용량 갯수
          properties:
            one-giga-volume-cnt: 
              type: integer 
              example: 3 
            one-hundred-giga-volume-cnt:
              type: integer 
              example: 2 
            five-hundreds-giga-volume-cnt:
              type : integer 
              example: 1 
        email-volume:
          type: object 
          description: 사용자가 추가한 공용 용량 갯수
          properties:
            one-giga-volume-cnt: 
              type: integer 
              example: 3 
            one-hundred-giga-volume-cnt:
              type: integer 
              example: 2 
            five-hundreds-giga-volume-cnt:
              type : integer 
              example: 1 
        contract-discount-period:
          type: string
          description: 약정할인 기간(서비스 신청일~종료일)
          format: yyyymmdd~yyyymmdd
          example: 20210301~202010501
        isERPConnection:
          type: string
          description : ERP 연동 여부 
          enum : ["Y","N"]
        license-start-date:
          type: string
          description: Bizstore 상품신청 일자, 라이선스 시작 일 (yyyyMMdd)
          example: "20201210"
        license-states-cd:
          type: string
          description: 라이선스 상태(사용중 = 0, 해지 = 1, 정지 = 2)
          example: "0"
    status:
      required:
      - mem-sq
      - reg-date
      - status
      - service-manager
      - service-engineer
      - user-id-for-kaoni
      properties:
        mem-sq:
          description: 고객 식별정보
          example: M12345
        license-start-date:
          description: 고객 신청일(kt cloud bizstore 신청기준)
          format: yyyymmdd
          example: 20210428
        reg-date:
          description: 고객 신청일(비즈플레이 가입기준)
          format: yyyymmdd
          example: 20210428
        status:
          type: string
          description: 0(설치진행중) / 1(설치 완료) / 98(삭제진행중) / (삭제 완료 - delete되서 값 없으면 401 코드 또는 "99" 값으로 리턴)
          example: "1"
        service-manager:
          description: 서비스 담당자 정보 
          example: 홍길동(010-3333-4444,honggildong@kt.com)
          format: name(010-nnnn-nnnn,name@domain)
        service-engineer:
          description: 서비스 엔지니어 정보
          example: 홍길동(010-3333-4444,honggildong@kt.com)
          format: name(010-nnnn-nnnn,name@domain)
        user-id-for-kaoni:
          type: string
          description: 회사 ID 정보 
          example: kaoni
        manager-id-for-kaoni:
          type: string
          description: 관리자 ID 정보 
          example: kaoniKing
  responses:
    "200":
      description: 성공, OK, 유효한 요청에 대한 예상된 응답
    "201":
      description: 성공, Created, 자원 생성 완료
    "202":
      description: 성공, Accepted, 시간 지연
    "400":
      description: 실패, Bad request
    "401":
      description: 실패, Unauthorized, 유저 권한 없음
    "403":
      description: 실패, Forbidden, 유저 권한 문제
    "404":
      description: 실패, Not Found, 찾지 못함.
    "405":
      description: 실패, Method not allowed, Request의 endpoint와 resource가 유효하지 않음.
    "406":
      description: 실패, 무료체험 고객
